In [1]:
import numpy as np

In [2]:
arr=np.array([7,9,8,4])
print(arr)

[7 9 8 4]


In [3]:
np.sum(arr)

28

In [4]:
np.min(arr)

4

In [5]:
np.max(arr)

9

In [6]:
np.mean(arr)

7.0

In [7]:
np.median(arr)

7.5

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr.shape

(4,)

In [10]:
np.append(arr,7)

array([7, 9, 8, 4, 7])

In [11]:
arr1=np.array([6,7,4,5,3,2])
arr2=np.array([9,5,8,0,2])
arr3=np.append(arr1,arr2)
arr3

array([6, 7, 4, 5, 3, 2, 9, 5, 8, 0, 2])

In [12]:
np.random.rand(3,4)

array([[0.99506768, 0.49690688, 0.09178521, 0.61989226],
       [0.84897859, 0.11397583, 0.58110716, 0.34459539],
       [0.28887551, 0.51785236, 0.91616339, 0.26571435]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr4=np.array([[2,6,7,3],[6,2,0,5]])
arr4

array([[2, 6, 7, 3],
       [6, 2, 0, 5]])

In [15]:
arrr=np.intersect1d(arr1,arr2)

In [16]:
arrr

array([2, 5])

In [17]:
np.union1d(arr1,arr2)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.setdiff1d(arr1,arr2)

array([3, 4, 6, 7])

In [20]:
np.setxor1d(arr1,arr2)

array([0, 3, 4, 6, 7, 8, 9])

In [21]:
array=np.array([1,1,9,5,0,1,3,3,5,7,5,3,9,0])
np.unique(array)

array([0, 1, 3, 5, 7, 9])

In [22]:
uniques,counts=np.unique(array,return_counts=True)

In [23]:
print(uniques)
print(counts)

[0 1 3 5 7 9]
[2 3 3 3 1 2]


In [24]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
arr5=[3,2,7,2,4,1]
np.repeat(arr5,2)

array([3, 3, 2, 2, 7, 7, 2, 2, 4, 4, 1, 1])

In [31]:
np.tile(arr5,2)

array([3, 2, 7, 2, 4, 1, 3, 2, 7, 2, 4, 1])

In [32]:
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
identity_matrix1=np.eye(3,4)
identity_matrix1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [35]:
np.diag([2,5,1,0,9])

array([[2, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9]])

In [38]:
array1=np.random.rand(4,4)
array1

array([[0.21685073, 0.76325758, 0.41679854, 0.95847946],
       [0.83462268, 0.62105055, 0.53644122, 0.89178276],
       [0.42574869, 0.82539971, 0.06506236, 0.433475  ],
       [0.38145139, 0.36540256, 0.13418191, 0.83458847]])

In [39]:
np.diag(array1)

array([0.21685073, 0.62105055, 0.06506236, 0.83458847])

In [41]:
array1.size

16

In [42]:
array1.ndim

2

In [44]:
np.random.randint(0,10,3)

array([6, 2, 8])

In [45]:
np.std(array1)

0.2738567252805595

In [46]:
np.var(array1)

0.07499750598139182

In [48]:
np.sort(array1,axis=1)

array([[0.21685073, 0.41679854, 0.76325758, 0.95847946],
       [0.53644122, 0.62105055, 0.83462268, 0.89178276],
       [0.06506236, 0.42574869, 0.433475  , 0.82539971],
       [0.13418191, 0.36540256, 0.38145139, 0.83458847]])

In [51]:
array1

array([[0.21685073, 0.76325758, 0.41679854, 0.95847946],
       [0.83462268, 0.62105055, 0.53644122, 0.89178276],
       [0.42574869, 0.82539971, 0.06506236, 0.433475  ],
       [0.38145139, 0.36540256, 0.13418191, 0.83458847]])

In [49]:
array1.T

array([[0.21685073, 0.83462268, 0.42574869, 0.38145139],
       [0.76325758, 0.62105055, 0.82539971, 0.36540256],
       [0.41679854, 0.53644122, 0.06506236, 0.13418191],
       [0.95847946, 0.89178276, 0.433475  , 0.83458847]])

In [53]:
array1.flatten()

array([0.21685073, 0.76325758, 0.41679854, 0.95847946, 0.83462268,
       0.62105055, 0.53644122, 0.89178276, 0.42574869, 0.82539971,
       0.06506236, 0.433475  , 0.38145139, 0.36540256, 0.13418191,
       0.83458847])

In [56]:
arr6=np.delete(array1,[0,2])

In [57]:
arr6

array([0.76325758, 0.95847946, 0.83462268, 0.62105055, 0.53644122,
       0.89178276, 0.42574869, 0.82539971, 0.06506236, 0.433475  ,
       0.38145139, 0.36540256, 0.13418191, 0.83458847])

In [61]:
arrk=[[2,3,1,4],[5,3,9,0]]
arrp=[[3,2,3,4],[5,4,2,3]]
arrs=np.concatenate((arrk,arrp),axis=1)

In [62]:
arrs

array([[2, 3, 1, 4, 3, 2, 3, 4],
       [5, 3, 9, 0, 5, 4, 2, 3]])

In [63]:
np.vstack((arrk,arrp))

array([[2, 3, 1, 4],
       [5, 3, 9, 0],
       [3, 2, 3, 4],
       [5, 4, 2, 3]])

In [64]:
np.hstack((arrp,arrk))

array([[3, 2, 3, 4, 2, 3, 1, 4],
       [5, 4, 2, 3, 5, 3, 9, 0]])